/* AUTO-GENERATED BY wasm2api. DO NOT EDIT. */
#pragma once

#include <stdint.h>
#include "wasm.h"

typedef struct basic_add_ctx_t basic_add_ctx_t;

basic_add_ctx_t* basic_add_init(wasm_runtime_t* rt, const uint8_t* wasm_bytes, size_t len);
void basic_add_free(basic_add_ctx_t* ctx);
wasm_module_t* basic_add_module(basic_add_ctx_t* ctx);
wasm_error_t basic_add_last_error(const basic_add_ctx_t* ctx);
const char* basic_add_last_error_string(const basic_add_ctx_t* ctx);
const char* basic_add_last_error_message(const basic_add_ctx_t* ctx);
const uint8_t* basic_add_embedded_wasm(size_t* out_len);
basic_add_ctx_t* basic_add_init_embedded(wasm_runtime_t* rt);

int32_t basic_add_wl_case(basic_add_ctx_t* ctx);
void basic_add_emscripten_stack_init(basic_add_ctx_t* ctx);
int32_t basic_add_emscripten_stack_get_free(basic_add_ctx_t* ctx);
int32_t basic_add_emscripten_stack_get_base(basic_add_ctx_t* ctx);
int32_t basic_add_emscripten_stack_get_end(basic_add_ctx_t* ctx);
void basic_add__emscripten_stack_restore(basic_add_ctx_t* ctx, int32_t arg0);
int32_t basic_add_emscripten_stack_get_current(basic_add_ctx_t* ctx);
