/* AUTO-GENERATED BY wasm2api. DO NOT EDIT. */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "wasm.h"

typedef struct session_math_init_options_t {
    wasm_runtime_t* runtime;
    const wasm_config_t* runtime_config;
} session_math_init_options_t;

void session_math_init_options_default(session_math_init_options_t* options);
wasm_error_t session_math_init(const uint8_t* wasm_bytes, size_t len, const session_math_init_options_t* options);
void session_math_free(void);
wasm_module_t* session_math_get_module(void);
wasm_runtime_t* session_math_get_runtime(void);
uint8_t* session_math_get_memory_ptr(void);
uint64_t session_math_get_memory_size(void);
const char* session_math_read_memory_string(uint64_t wasm_ptr, char* buffer, size_t max_len);
bool session_math_read_memory(uint64_t wasm_ptr, void* dest, size_t len);
bool session_math_write_memory(uint64_t wasm_ptr, const void* src, size_t len);
uint32_t session_math_get_required_features(void);
wasm_error_t session_math_get_last_error(void);
const char* session_math_get_last_error_string(void);
const char* session_math_get_last_error_message(void);
const uint8_t* session_math_get_embedded_wasm(size_t* out_len);
wasm_error_t session_math_init_embedded(const session_math_init_options_t* options);

double session_math_add(double arg0, double arg1);
double session_math_sub(double arg0, double arg1);
double session_math_pow(double arg0, double arg1);
double session_math_exp(double arg0);
void session_math_init_state(void);
int32_t session_math_ready(void);
int32_t session_math_add_scaled(int32_t arg0, int32_t arg1);
void session_math_set_bias(int32_t arg0);
int32_t session_math_get_bias(void);
int32_t session_math_get_total(void);
void session_math_reset_total(void);
