// This gets compiled to WASM and has a wrapper generated by wasm2api.c. See session_math_demo.c for an example of using the wrapper.
#include <stdint.h>

static double session_math_abs(double value) {
	return value < 0.0 ? -value : value;
}

static double session_math_exp_approx(double value) {
	static const double k_max_input = 20.0;
	static const int k_terms = 12;
	double sum = 1.0;
	double term = 1.0;
	int i;
	int negate = 0;

	if (value == 0.0) return 1.0;
	if (value < 0.0) {
		negate = 1;
		value = -value;
	}
	if (value > k_max_input) value = k_max_input;

	for (i = 1; i <= k_terms; i++) {
		term *= value / (double)i;
		sum += term;
	}

	return negate ? 1.0 / sum : sum;
}

static double session_math_log_approx(double value) {
	static const double k_ln2 = 0.6931471805599453;
	double scaled = value;
	double z;
	double z_sq;
	double series;
	int shift = 0;

	if (value <= 0.0) return 0.0;

	while (scaled > 2.0) {
		scaled *= 0.5;
		shift++;
	}
	while (scaled < 0.5) {
		scaled *= 2.0;
		shift--;
	}

	z = (scaled - 1.0) / (scaled + 1.0);
	z_sq = z * z;
	series = z;
	series += (z * z_sq) / 3.0;
	series += (z * z_sq * z_sq) / 5.0;
	series += (z * z_sq * z_sq * z_sq) / 7.0;
	series += (z * z_sq * z_sq * z_sq * z_sq) / 9.0;

	return 2.0 * series + (double)shift * k_ln2;
}

static double session_math_pow_approx(double base, double exponent) {
	double rounded = exponent >= 0.0 ? (double)((int64_t)(exponent + 0.5))
									  : (double)((int64_t)(exponent - 0.5));
	double result = 1.0;
	double factor = base;
	int64_t integer_exp;
	int invert = 0;

	if (base == 0.0) return exponent > 0.0 ? 0.0 : 1.0;
	if (session_math_abs(exponent - rounded) <= 1e-9) {
		integer_exp = (int64_t)rounded;
		if (integer_exp < 0) {
			invert = 1;
			integer_exp = -integer_exp;
		}
		while (integer_exp > 0) {
			if ((integer_exp & 1) != 0) result *= factor;
			factor *= factor;
			integer_exp >>= 1;
		}
		return invert ? 1.0 / result : result;
	}
	if (base < 0.0) return 0.0;
	return session_math_exp_approx(exponent * session_math_log_approx(base));
}

double add(double lhs, double rhs) {
	return lhs + rhs;
}

double sub(double lhs, double rhs) {
	return lhs - rhs;
}

#define export(name) __attribute__((export_name(name)))

export("pow") double session_math_pow_export(double base,
													   double exponent) {
	return session_math_pow_approx(base, exponent);
}

export("exp") double session_math_exp_export(double value) {
	return session_math_exp_approx(value);
}

static int32_t g_bias;
static int32_t g_total;
static int32_t g_initialized;

void init_state(void) {
	g_bias = 7;
	g_total = 100;
	g_initialized = 1;
}

int32_t ready(void) {
	return g_initialized;
}

int32_t add_scaled(int32_t lhs, int32_t rhs) {
	int32_t value = lhs * 2 + rhs + g_bias;

	g_total += value;
	return g_total;
}

void set_bias(int32_t bias) {
	g_bias = bias;
}

int32_t get_bias(void) {
	return g_bias;
}

int32_t get_total(void) {
	return g_total;
}

void reset_total(void) {
	g_total = 0;
}