/* AUTO-GENERATED BY wasm2api. DO NOT EDIT. */
#pragma once

#include <stdint.h>
#include "wasm.h"

typedef struct session_math_ctx_t session_math_ctx_t;
typedef struct session_math_init_options_t {
    wasm_runtime_t* runtime;
    const wasm_config_t* runtime_config;
} session_math_init_options_t;

void session_math_init_options_default(session_math_init_options_t* options);
session_math_ctx_t* session_math_init(const uint8_t* wasm_bytes, size_t len, const session_math_init_options_t* options);
void session_math_free(session_math_ctx_t* ctx);
wasm_module_t* session_math_module(session_math_ctx_t* ctx);
wasm_runtime_t* session_math_runtime(session_math_ctx_t* ctx);
uint32_t session_math_required_features(void);
wasm_error_t session_math_last_error(const session_math_ctx_t* ctx);
const char* session_math_last_error_string(const session_math_ctx_t* ctx);
const char* session_math_last_error_message(const session_math_ctx_t* ctx);
const uint8_t* session_math_embedded_wasm(size_t* out_len);
session_math_ctx_t* session_math_init_embedded(const session_math_init_options_t* options);

void session_math_init_state(session_math_ctx_t* ctx);
int32_t session_math_ready(session_math_ctx_t* ctx);
int32_t session_math_add_scaled(session_math_ctx_t* ctx, int32_t arg0, int32_t arg1);
void session_math_set_bias(session_math_ctx_t* ctx, int32_t arg0);
int32_t session_math_get_bias(session_math_ctx_t* ctx);
int32_t session_math_get_total(session_math_ctx_t* ctx);
void session_math_reset_total(session_math_ctx_t* ctx);
