/* AUTO-GENERATED BY wasm2api. DO NOT EDIT. */
#include "session_math.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const uint8_t session_math_embedded_wasm_data[] = {
    0x00, 0x61, 0x73, 0x6D, 0x01, 0x00, 0x00, 0x00, 0x01, 0x12, 0x04, 0x60, 
    0x00, 0x00, 0x60, 0x00, 0x01, 0x7F, 0x60, 0x02, 0x7F, 0x7F, 0x01, 0x7F, 
    0x60, 0x01, 0x7F, 0x00, 0x03, 0x0A, 0x09, 0x00, 0x01, 0x02, 0x03, 0x01, 
    0x01, 0x00, 0x03, 0x01, 0x04, 0x05, 0x01, 0x70, 0x01, 0x01, 0x01, 0x05, 
    0x06, 0x01, 0x01, 0x82, 0x02, 0x82, 0x02, 0x06, 0x08, 0x01, 0x7F, 0x01, 
    0x41, 0x90, 0x88, 0x04, 0x0B, 0x07, 0xB3, 0x01, 0x0B, 0x06, 0x6D, 0x65, 
    0x6D, 0x6F, 0x72, 0x79, 0x02, 0x00, 0x0A, 0x69, 0x6E, 0x69, 0x74, 0x5F, 
    0x73, 0x74, 0x61, 0x74, 0x65, 0x00, 0x00, 0x05, 0x72, 0x65, 0x61, 0x64, 
    0x79, 0x00, 0x01, 0x0A, 0x61, 0x64, 0x64, 0x5F, 0x73, 0x63, 0x61, 0x6C, 
    0x65, 0x64, 0x00, 0x02, 0x08, 0x73, 0x65, 0x74, 0x5F, 0x62, 0x69, 0x61, 
    0x73, 0x00, 0x03, 0x08, 0x67, 0x65, 0x74, 0x5F, 0x62, 0x69, 0x61, 0x73, 
    0x00, 0x04, 0x09, 0x67, 0x65, 0x74, 0x5F, 0x74, 0x6F, 0x74, 0x61, 0x6C, 
    0x00, 0x05, 0x0B, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5F, 0x74, 0x6F, 0x74, 
    0x61, 0x6C, 0x00, 0x06, 0x19, 0x5F, 0x5F, 0x69, 0x6E, 0x64, 0x69, 0x72, 
    0x65, 0x63, 0x74, 0x5F, 0x66, 0x75, 0x6E, 0x63, 0x74, 0x69, 0x6F, 0x6E, 
    0x5F, 0x74, 0x61, 0x62, 0x6C, 0x65, 0x01, 0x00, 0x19, 0x5F, 0x65, 0x6D, 
    0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x65, 0x6E, 0x5F, 0x73, 0x74, 0x61, 
    0x63, 0x6B, 0x5F, 0x72, 0x65, 0x73, 0x74, 0x6F, 0x72, 0x65, 0x00, 0x07, 
    0x1C, 0x65, 0x6D, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x65, 0x6E, 0x5F, 
    0x73, 0x74, 0x61, 0x63, 0x6B, 0x5F, 0x67, 0x65, 0x74, 0x5F, 0x63, 0x75, 
    0x72, 0x72, 0x65, 0x6E, 0x74, 0x00, 0x08, 0x0A, 0xA6, 0x01, 0x09, 0x24, 
    0x00, 0x41, 0x00, 0x41, 0xE4, 0x00, 0x36, 0x02, 0x84, 0x88, 0x80, 0x80, 
    0x00, 0x41, 0x00, 0x41, 0x07, 0x36, 0x02, 0x80, 0x88, 0x80, 0x80, 0x00, 
    0x41, 0x00, 0x41, 0x01, 0x3A, 0x00, 0x88, 0x88, 0x80, 0x80, 0x00, 0x0B, 
    0x0B, 0x00, 0x41, 0x00, 0x2D, 0x00, 0x88, 0x88, 0x80, 0x80, 0x00, 0x0B, 
    0x2B, 0x00, 0x41, 0x00, 0x20, 0x00, 0x41, 0x01, 0x74, 0x20, 0x01, 0x6A, 
    0x41, 0x00, 0x28, 0x02, 0x80, 0x88, 0x80, 0x80, 0x00, 0x6A, 0x41, 0x00, 
    0x28, 0x02, 0x84, 0x88, 0x80, 0x80, 0x00, 0x6A, 0x22, 0x00, 0x36, 0x02, 
    0x84, 0x88, 0x80, 0x80, 0x00, 0x20, 0x00, 0x0B, 0x0D, 0x00, 0x41, 0x00, 
    0x20, 0x00, 0x36, 0x02, 0x80, 0x88, 0x80, 0x80, 0x00, 0x0B, 0x0B, 0x00, 
    0x41, 0x00, 0x28, 0x02, 0x80, 0x88, 0x80, 0x80, 0x00, 0x0B, 0x0B, 0x00, 
    0x41, 0x00, 0x28, 0x02, 0x84, 0x88, 0x80, 0x80, 0x00, 0x0B, 0x0D, 0x00, 
    0x41, 0x00, 0x41, 0x00, 0x36, 0x02, 0x84, 0x88, 0x80, 0x80, 0x00, 0x0B, 
    0x0A, 0x00, 0x20, 0x00, 0x24, 0x80, 0x80, 0x80, 0x80, 0x00, 0x0B, 0x08, 
    0x00, 0x23, 0x80, 0x80, 0x80, 0x80, 0x00, 0x0B, 0x00, 0x94, 0x01, 0x0F, 
    0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5F, 0x66, 0x65, 0x61, 0x74, 0x75, 
    0x72, 0x65, 0x73, 0x08, 0x2B, 0x0B, 0x62, 0x75, 0x6C, 0x6B, 0x2D, 0x6D, 
    0x65, 0x6D, 0x6F, 0x72, 0x79, 0x2B, 0x0F, 0x62, 0x75, 0x6C, 0x6B, 0x2D, 
    0x6D, 0x65, 0x6D, 0x6F, 0x72, 0x79, 0x2D, 0x6F, 0x70, 0x74, 0x2B, 0x16, 
    0x63, 0x61, 0x6C, 0x6C, 0x2D, 0x69, 0x6E, 0x64, 0x69, 0x72, 0x65, 0x63, 
    0x74, 0x2D, 0x6F, 0x76, 0x65, 0x72, 0x6C, 0x6F, 0x6E, 0x67, 0x2B, 0x0A, 
    0x6D, 0x75, 0x6C, 0x74, 0x69, 0x76, 0x61, 0x6C, 0x75, 0x65, 0x2B, 0x0F, 
    0x6D, 0x75, 0x74, 0x61, 0x62, 0x6C, 0x65, 0x2D, 0x67, 0x6C, 0x6F, 0x62, 
    0x61, 0x6C, 0x73, 0x2B, 0x13, 0x6E, 0x6F, 0x6E, 0x74, 0x72, 0x61, 0x70, 
    0x70, 0x69, 0x6E, 0x67, 0x2D, 0x66, 0x70, 0x74, 0x6F, 0x69, 0x6E, 0x74, 
    0x2B, 0x0F, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6E, 0x63, 0x65, 0x2D, 
    0x74, 0x79, 0x70, 0x65, 0x73, 0x2B, 0x08, 0x73, 0x69, 0x67, 0x6E, 0x2D, 
    0x65, 0x78, 0x74
};
static const size_t session_math_embedded_wasm_len = 567;

struct session_math_ctx_t {
    wasm_runtime_t* rt;
    wasm_runtime_t owned_rt;
    wasm_module_t* mod;
    wasm_error_t last_error;
    char last_error_msg[256];
    int owns_runtime;
    int runtime_initialized;
    uint32_t idx_init_init_state;
    uint32_t idx_init_state;
    uint32_t idx_ready;
    uint32_t idx_add_scaled;
    uint32_t idx_set_bias;
    uint32_t idx_get_bias;
    uint32_t idx_get_total;
    uint32_t idx_reset_total;
};

static const uint32_t session_math_required_features_mask = 40u;

static void session_math_set_error(session_math_ctx_t* ctx, wasm_error_t err, const char* message) {
    if (!ctx) return;
    ctx->last_error = err;
    snprintf(ctx->last_error_msg, sizeof(ctx->last_error_msg), "%s",
             message ? message : "");
    if (!ctx->rt) return;
    ctx->rt->last_error = err;
    snprintf(ctx->rt->error_msg, sizeof(ctx->rt->error_msg), "%s",
             message ? message : "");
}

static void session_math_clear_error(session_math_ctx_t* ctx) {
    if (!ctx) return;
    ctx->last_error = WASM_OK;
    ctx->last_error_msg[0] = '\0';
    if (!ctx->rt) return;
    ctx->rt->last_error = WASM_OK;
    ctx->rt->error_msg[0] = '\0';
}

static void session_math_capture_runtime_error(session_math_ctx_t* ctx, wasm_error_t err, const char* fallback) {
    const char* message = fallback;

    if (ctx && ctx->rt && ctx->rt->error_msg[0]) message = ctx->rt->error_msg;
    if (!message) message = wasm_error_string(err);
    session_math_set_error(ctx, err, message);
}

static void session_math_configure_runtime(wasm_runtime_t* rt) {
    if (!rt) return;
    rt->enabled_features = session_math_required_features_mask;
}

void session_math_init_options_default(session_math_init_options_t* options) {
    if (!options) return;
    memset(options, 0, sizeof(*options));
}

session_math_ctx_t* session_math_init(const uint8_t* wasm_bytes, size_t len, const session_math_init_options_t* options) {
    session_math_ctx_t* ctx;
    wasm_runtime_t* rt = NULL;
    const wasm_config_t* runtime_config = NULL;
    wasm_error_t err;

    if (!wasm_bytes) return NULL;
    ctx = (void*)calloc(1u, sizeof(*ctx));
    if (!ctx) return NULL;
    if (options) {
        rt = options->runtime;
        runtime_config = options->runtime_config;
    }
    if (rt) {
        ctx->rt = rt;
    } else {
        ctx->rt = &ctx->owned_rt;
        err = wasm_init(ctx->rt, runtime_config);
        if (err != WASM_OK) {
            session_math_capture_runtime_error(ctx, err, "runtime init failed");
            return ctx;
        }
        ctx->owns_runtime = 1;
        ctx->runtime_initialized = 1;
    }
    rt = ctx->rt;
    session_math_configure_runtime(ctx->rt);
    ctx->mod = wasm_load(ctx->rt, wasm_bytes, len);
    if (!ctx->mod) {
        session_math_capture_runtime_error(ctx, ctx->rt->last_error, "failed to load module");
        return ctx;
    }
    wasm_module_set_userdata(ctx->mod, ctx);
    if (!wasm_find_export(ctx->mod, "init_state", NULL, &ctx->idx_init_init_state)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "init export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "init_state", NULL, &ctx->idx_init_state)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "ready", NULL, &ctx->idx_ready)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "add_scaled", NULL, &ctx->idx_add_scaled)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "set_bias", NULL, &ctx->idx_set_bias)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "get_bias", NULL, &ctx->idx_get_bias)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "get_total", NULL, &ctx->idx_get_total)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    if (!wasm_find_export(ctx->mod, "reset_total", NULL, &ctx->idx_reset_total)) {
        session_math_set_error(ctx, WASM_ERR_UNDEFINED_EXPORT, "cached export missing");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    err = wasm_call_index(ctx->mod, ctx->idx_init_init_state, NULL, 0, NULL, 0);
    if (err != WASM_OK) {
        session_math_capture_runtime_error(ctx, err, "module init export failed");
        wasm_free_module(ctx->mod);
        ctx->mod = NULL;
        return ctx;
    }
    session_math_clear_error(ctx);
    return ctx;
}

void session_math_free(session_math_ctx_t* ctx) {
    if (!ctx) return;
    if (ctx->mod) wasm_free_module(ctx->mod);
    if (ctx->owns_runtime && ctx->runtime_initialized) wasm_destroy(&ctx->owned_rt);
    free(ctx);
}

wasm_module_t* session_math_module(session_math_ctx_t* ctx) {
    return ctx ? ctx->mod : NULL;
}

wasm_runtime_t* session_math_runtime(session_math_ctx_t* ctx) {
    return ctx ? ctx->rt : NULL;
}

uint32_t session_math_required_features(void) {
    return session_math_required_features_mask;
}

wasm_error_t session_math_last_error(const session_math_ctx_t* ctx) {
    if (!ctx) return WASM_ERR_MALFORMED;
    return ctx->last_error;
}

const char* session_math_last_error_string(const session_math_ctx_t* ctx) {
    return wasm_error_string(session_math_last_error(ctx));
}

const char* session_math_last_error_message(const session_math_ctx_t* ctx) {
    if (!ctx) return "invalid context";
    return ctx->last_error_msg;
}

const uint8_t* session_math_embedded_wasm(size_t* out_len) {
    if (out_len) *out_len = session_math_embedded_wasm_len;
    return session_math_embedded_wasm_data;
}

session_math_ctx_t* session_math_init_embedded(const session_math_init_options_t* options) {
    return session_math_init(session_math_embedded_wasm_data, session_math_embedded_wasm_len, options);
}

void session_math_init_state(session_math_ctx_t* ctx) {
    wasm_error_t err;

    if (!ctx || !ctx->mod) return;
    err = wasm_call_index(ctx->mod, ctx->idx_init_state, NULL, 0, NULL, 0);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return; }
    session_math_clear_error(ctx);
    return;
}

int32_t session_math_ready(session_math_ctx_t* ctx) {
    int32_t ret = 0;
    wasm_error_t err;
    wasm_value_t results[1];

    if (!ctx || !ctx->mod) return ret;
    err = wasm_call_index(ctx->mod, ctx->idx_ready, NULL, 0, results, 1);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return ret; }
    ret = results[0].of.i32;
    session_math_clear_error(ctx);
    return ret;
}

int32_t session_math_add_scaled(session_math_ctx_t* ctx, int32_t arg0, int32_t arg1) {
    int32_t ret = 0;
    wasm_error_t err;
    wasm_value_t args[2];
    wasm_value_t results[1];

    if (!ctx || !ctx->mod) return ret;
    args[0] = wasm_i32(arg0);
    args[1] = wasm_i32(arg1);
    err = wasm_call_index(ctx->mod, ctx->idx_add_scaled, args, 2, results, 1);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return ret; }
    ret = results[0].of.i32;
    session_math_clear_error(ctx);
    return ret;
}

void session_math_set_bias(session_math_ctx_t* ctx, int32_t arg0) {
    wasm_error_t err;
    wasm_value_t args[1];

    if (!ctx || !ctx->mod) return;
    args[0] = wasm_i32(arg0);
    err = wasm_call_index(ctx->mod, ctx->idx_set_bias, args, 1, NULL, 0);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return; }
    session_math_clear_error(ctx);
    return;
}

int32_t session_math_get_bias(session_math_ctx_t* ctx) {
    int32_t ret = 0;
    wasm_error_t err;
    wasm_value_t results[1];

    if (!ctx || !ctx->mod) return ret;
    err = wasm_call_index(ctx->mod, ctx->idx_get_bias, NULL, 0, results, 1);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return ret; }
    ret = results[0].of.i32;
    session_math_clear_error(ctx);
    return ret;
}

int32_t session_math_get_total(session_math_ctx_t* ctx) {
    int32_t ret = 0;
    wasm_error_t err;
    wasm_value_t results[1];

    if (!ctx || !ctx->mod) return ret;
    err = wasm_call_index(ctx->mod, ctx->idx_get_total, NULL, 0, results, 1);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return ret; }
    ret = results[0].of.i32;
    session_math_clear_error(ctx);
    return ret;
}

void session_math_reset_total(session_math_ctx_t* ctx) {
    wasm_error_t err;

    if (!ctx || !ctx->mod) return;
    err = wasm_call_index(ctx->mod, ctx->idx_reset_total, NULL, 0, NULL, 0);
    if (err != WASM_OK) { session_math_capture_runtime_error(ctx, err, NULL); return; }
    session_math_clear_error(ctx);
    return;
}

